services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      redis-node-a:
        condition: service_healthy
      redis-node-b:
        condition: service_healthy
      redis-node-c:
        condition: service_healthy
    environment:
      - REDIS_A_HOST=redis-node-a
      - REDIS_B_HOST=redis-node-b
      - REDIS_C_HOST=redis-node-c

  redis-node-a:
    image: redis
    container_name: redis-node-a
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 2s
      retries: 10

  redis-node-b:
    image: redis
    container_name: redis-node-b
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 2s
      retries: 10

  redis-node-c:
    image: redis
    container_name: redis-node-c
    ports:
      - "6381:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 2s
      retries: 10